homo_sapiens_GCA_000001405_27:
  Gene:
    ENSG00000139618:
      label: 'BRCA2'
      description: 'BRCA2, DNA repair associated'
      spliced_length: 84793
      strand: 'forward'
      bio_type: 'Protein coding'
      location:
        chromosome: '13'
        start: 32315474
        end: 32400266
      child_objects:
        Transcript:
            ENST00000380152.7:
              additional_info: 'Protein coding'
              description: 'BRCA2, DNA repair associated'
              colour: 'BLUE'
              support_level: 'Canonical'
              track_id: 'gene-feat-1'
triticum_aestivum_GCA_900519105_1:
  Gene:
    TraesCS3D02G273600:
      label: 'TraesCS3D02G273600'
      description: 'Heat shock protein 101 '
      spliced_length: 84793
      strand: 'reverse'
      bio_type: 'Protein coding'
      location:
        chromosome: '3D'
        start: 379535906
        end: 379539827
      child_objects:
        Transcript:
            TraesCS3D02G273600.1:
              additional_info: 'Protein coding'
              description: 'Heat shock protein 101 '
              colour: 'BLUE'
              support_level: 'Canonical'
              track_id: 'gene-feat-1'
homo_sapiens_GCA_000001405_14:
  Gene:
    ENSG00000139618:
      label: 'BRCA2'
      description: 'breast cancer 2, early onset'
      spliced_length: 84793
      strand: 'forward'
      bio_type: 'Protein coding'
      location:
        chromosome: '13'
        start: 32889611
        end: 32973805
      child_objects:
        Transcript:
            ENST00000544455.1:
              additional_info: 'Protein coding'
              description: 'breast cancer 2, early onset'
              colour: 'BLUE'
              support_level: 'Canonical'
              track_id: 'gene-feat-1'
escherichia_coli_str_k_12_substr_mg1655_GCA_000005845_2:
  Gene:
    b2614:
      label: 'grpE'
      description: 'heat shock protein'
      spliced_length: 84793
      strand: 'reverse'
      bio_type: 'Protein coding'
      location:
        chromosome: 'Chromosome'
        start: 2750115
        end: 2750708
      child_objects:
        Transcript:
            AAC75663:
              additional_info: 'Protein coding'
              description: 'heat shock protein'
              colour: 'BLUE'
              support_level: 'Canonical'
              track_id: 'gene-feat-1'
saccharomyces_cerevisiae_GCA_000146045_2:
  Gene:
    YDL168W:
      label: 'SFA1'
      description: 'Bifunctional alcohol dehydrogenase and formaldehyde dehydrogenase; formaldehyde dehydrogenase activity is glutathione-dependent; functions in formaldehyde detoxification and formation of long chain and complex alcohols, regulated by Hog1p-Sko1p; protein abundance increases in response to DNA replication stress'
      spliced_length: 84793
      strand: 'forward'
      bio_type: 'Protein coding'
      location:
        chromosome: 'IV'
        start: 159604
        end: 160764
      child_objects:
        Transcript:
            YDL168W_mRNA:
              additional_info: 'Protein coding'
              description: 'Bifunctional alcohol dehydrogenase and formaldehyde dehydrogenase; formaldehyde dehydrogenase activity is glutathione-dependent; functions in formaldehyde detoxification and formation of long chain and complex alcohols, regulated by Hog1p-Sko1p; protein abundance increases in response to DNA replication stress'
              colour: 'BLUE'
              support_level: 'Canonical'
              track_id: 'gene-feat-1'
caenorhabditis_elegans_GCA_000002985_3:
  Gene:
    WBGene00004893:
      label: 'sms-2'
      description: 'Phosphatidylcholine:ceramide cholinephosphotransferase 2'
      spliced_length: 84793
      strand: 'reverse'
      bio_type: 'Protein coding'
      location:
        chromosome: 'X'
        start: 944826
        end: 948883
      child_objects:
        Transcript:
            F53H8.4:
              additional_info: 'Protein coding'
              description: 'Phosphatidylcholine:ceramide cholinephosphotransferase 2'
              colour: 'BLUE'
              support_level: 'Canonical'
              track_id: 'gene-feat-1'
plasmodium_falciparum_GCA_000002765_2:
  Gene:
    PF3D7_1143500:
      label: 'PF3D7_1143500'
      description: 'conserved Plasmodium protein, unknown function'
      spliced_length: 84793
      strand: 'reverse'
      bio_type: 'Protein coding'
      location:
        chromosome: '11'
        start: 1737256
        end: 1740029
      child_objects:
        Transcript:
            CZT99098:
              additional_info: 'Protein coding'
              description: 'conserved Plasmodium protein, unknown function'
              colour: 'BLUE'
              support_level: 'Canonical'
              track_id: 'gene-feat-1'
