track_categories:
     - label: 'Genes & transcripts'
       track_category_id: 'genes-transcripts'
       track_list:
         - additional_info: 'Forward strand'
           color: 'DARK_GREY'
           label: 'Protein coding genes'
           track_id: 'track:gene-pc-fwd'
         - additional_info: 'Forward strand'
           color: 'GREY'
           label: 'Other genes'
           track_id: 'track:gene-other-fwd'
         - additional_info: 'Reverse strand'
           color: 'DARK_GREY'
           label: 'Protein coding genes'
           track_id: 'track:gene-pc-rev'
         - additional_info: 'Reverse strand'
           color: 'GREY'
           label: 'Other genes'
           track_id: 'track:gene-other-rev'
       types:
         - 'Genomic'

     - label: 'Assembly'
       track_category_id: 'assembly'
       track_list:
          - label: 'Contigs'
            track_id: 'track:contig'
          - label: '%GC'
            track_id: 'track:gc'
       types:
         - 'Genomic'

     - label: 'Comparative genomics'
       track_category_id: 'comparative-genomics'
       track_list: []
       types:
         - 'Genomic'

     - track_id: 'Short variants'
       track_category_id: 'short-variants'
       track_list:
        - label: '1000 Genomes all SNPs & indels'
          track_id: 'track:variant'
       types:
         - 'Variation'

     - label: 'Somatic variants'
       track_category_id: 'somatic-variants'
       track_list: []
       types:
         - 'Variation'

     - label: 'Structural variants'
       track_category_id: 'structural-variants'
       track_list: []
       types:
         - 'Variation'

     - label: 'Experiment design'
       track_category_id: 'experiment-design'
       track_list: []
       types:
         - 'Genomic'
         - 'Expression'
         - 'Variation'

     - label: 'References & evidence'
       track_category_id: 'references-evidence'
       track_list: []
       types:
         - 'Genomic'

     - label: 'Regulatory features'
       track_category_id: 'regulatory-features'
       track_list: []
       types:
         - 'Expression'

     - label: 'Gene expression correlations'
       track_category_id: 'gene-expression'
       track_list: []
       types:
         - 'Expression'

     - label: 'Other regulatory regions'
       track_category_id: 'regulatory-regions'
       track_list: []
       types:
         - 'Expression'
