stages:
  - test_deploy

variables:
  DOCKER_TLS_CERTDIR: ""


Deploy:feature:
  stage: test_deploy
  image: dockerhub.ebi.ac.uk/kamal/deploy-tools:0.1

  environment:
    name : exp-staging

  before_script:
  - kubectl get ns
  - kubectl config view
