#
#    See the NOTICE file distributed with this work for additional information
#    regarding copyright ownership.
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#    http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
#

# CI/CD Pipeline
# dev branch -> staging
# master branch -> internal ( all 45000 species)
# master branch -> live

# Define stages for the CI/CD pipeline
stages:
  - build_docker_image
  - test
  - deploy

# Template to build to docker image
.build:
  stage: build_docker_image
  image: docker
  services:
    - docker:dind
  before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
  - docker build -t ${CONTAINER_IMAGE} --no-cache -f docker/${DOCKERFILE} .
  - docker push ${CONTAINER_IMAGE}
  #- docker rmi ${CONTAINER_IMAGE}
  - docker logout $CI_REGISTRY

# Template to deploy to WP k8s cluster
.deploy-wp:
  stage: deploy
  image: dockerhub.ebi.ac.uk/kamal/deploy-tools:0.1

  script:
  - git clone https://gitlab.ebi.ac.uk/ensembl-web/ensembl-k8s-manifests.git
  - git -C ensembl-k8s-manifests/ checkout wp-k8s
  - sed -i "s#<DOCKER_IMAGE>#${CONTAINER_IMAGE}#g" ensembl-k8s-manifests/ensembl_genome_search_deployment.yaml
  - kubectl apply -f ensembl-k8s-manifests/ensembl_genome_search_deployment.yaml

.deploy-wp-review:
  stage: deploy
  image: dockerhub.ebi.ac.uk/kamal/deploy-tools:0.1

  script:
  - git clone https://gitlab.ebi.ac.uk/ensembl-web/ensembl-k8s-manifests.git
  - git -C ensembl-k8s-manifests/ checkout wp-k8s-review
  - sed -i "s#<DOCKER_IMAGE>#${CONTAINER_IMAGE}#g" ensembl-k8s-manifests/ensembl_genome_search_deployment.yaml
  - sed -i "s#<DEPLOYMENT_ENV>#${CI_COMMIT_REF_SLUG}#g" ensembl-k8s-manifests/ensembl_genome_search_deployment.yaml
  - kubectl apply -f ensembl-k8s-manifests/ensembl_genome_search_deployment.yaml

# Template to deploy to staging, internal, prod
.deploy-wp40:
  stage: deploy
  image: dockerhub.ebi.ac.uk/ensembl-web/deploy-tools:0.6
  script:
    - git clone https://gitlab.ebi.ac.uk/ensembl-web/ensembl-k8s-manifests.git
    - git -C ensembl-k8s-manifests/ checkout k8s123-migration
    - cd ensembl-k8s-manifests/ensembl-genome-search
    - kustomize edit set image DOCKER_IMAGE=${{CONTAINER_IMAGE}}
    - kubectl apply -k ./

variables:
  CONTAINER_IMAGE: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}
  DOCKERFILE: Dockerfile.prod
  DOCKER_TLS_CERTDIR: ""

# Run Tests
Test:
  stage: test

  image: ${CONTAINER_IMAGE}

  script:
    - python -m unittest discover -s tests

# Build docker image for live/Stage environment
Docker-IMG:
  extends: .build

  only:
  - dev
  - master

# Build docker image for internal environment
Docker-IMG:internal:
  extends: .build
  variables:
    CONTAINER_IMAGE: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}-internal
    DOCKERFILE: Dockerfile.internal

  only:
  - dev

# Build docker image for feature_branch environment
Docker-IMG:review:
  extends: .build
  variables:
    DOCKERFILE: Dockerfile.feature

  except:
  - dev
  - master  
  - /^nodeploy\/.*$/

# Deploy staging to WP-HX cluster
Staging:WP-HX:
  extends: .deploy-wp
  environment:
    name : wp-hx-staging

  only:
  - dev

# Deploy staging to WP-HH cluster
Staging:WP-HH:
  extends: .deploy-wp
  environment:
    name : wp-hh-staging

  only:
  - dev

# Deploy live to WP-HH cluster
Live:WP-HX:
  extends: .deploy-wp
  environment:
    name : wp-hx-live

  only:
  - master

# Deploy live to WP-HH cluster
Live:WP-HH:
  extends: .deploy-wp
  environment:
    name : wp-hh-live

  only:
  - master

# Deploy internal to WP-HX cluster
Internal:WP-HX:
  extends: .deploy-wp
  variables:
    CONTAINER_IMAGE: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}-internal
  environment:
    name : wp-hx-internal

  only:
  - dev

# Deploy internal to WP-HH cluster
Internal:WP-HH:
  extends: .deploy-wp
  variables:
    CONTAINER_IMAGE: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}-internal
  environment:
    name : wp-hh-internal

  only:
  - dev

# Deploy dev to WP-HX cluster
Dev:WP-HX:
  extends: .deploy-wp
  environment:
    name : wp-hx-dev

  only:
  - dev

# Deploy Review apps to WP-HX k8s cluster
Review:WP-HX:
  extends: .deploy-wp-review
  environment:
    name : wp-hx-dev
  variables:
    DEPLOYENV: ${CI_COMMIT_REF_SLUG}

  except:
  - dev
  - master  
  - /^nodeploy\/.*$/

Live:wp40:HL:
  extends: .deploy-wp40
  environment:
    name: wp40-hl-prod
  rules:
    - if: '$CI_DEPLOY_FREEZE == null && $CI_COMMIT_BRANCH == "k8s-2020-genome-search"'
