openapi: 3.0.1
info:
  title: Ensembl - 2020
  description: API for 2020.ensembl.org
  contact:
    email: kamal@ebi.ac.uk
  version: 0.0.1
servers:
- url: https://2020.ensembl.org
- url: http://2020.ensembl.org
tags:
- name: api
  description: Genome searcch
paths:
  /api/genome/info/:
    get:
      tags:
      - api
      summary: Returns information about particular genome
      description: Returns a single genome
      parameters:
      - name: genome_id
        in: query
        description: ID of genome to return
        required: true
        schema:
          type: string
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Genome'
        400:
          description: Invalid Genome ID
          content: {}
        404:
          description: Genome not found
          content: {}
      security:
      - api_key: []
  /api/popular_genomes/:
    get:
      tags:
      - api
      summary: Get popular genomes
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  popular_species:
                    type: array
                    items:
                      $ref: '#/components/schemas/Genome'
        400:
          description: Invalid Genome ID
          content: {}
        404:
          description: Genome not found
          content: {}
      security:
      - api_key: []
  /api/alternative_assemblies/:
    get:
      tags:
      - api
      summary: Get alternative assemblies
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  alternate_assemblies:
                    type: array
                    items:
                      $ref: '#/components/schemas/Assembly'
        400:
          description: Invalid Genome ID
          content: {}
        404:
          description: Alternate assemblies not found
          content: {}
      security:
      - api_key: []
  /api/genome/track_categories/:
    get:
      tags:
      - api
      summary: Returns track ctegories for given genome_id
      description: Returns track categories for given genome
      parameters:
      - name: genome_id
        in: query
        description: genome_id for which track categories are requested
        required: true
        schema:
          type: string
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  track_categories:
                    type: array
                    items:
                      $ref: '#/components/schemas/TrackCategory'
        400:
          description: Invalid Genome ID
          content: {}
        404:
          description: Track categories not found
          content: {}
      security:
      - api_key: []  
components:
  schemas:
    Genome:
      type: object
      properties:
        assembly_name:
          type: string
          example: GRCh38.p12
        common_name:
          type: string
          example: Human
        genome_id:
          type: string
          example: homo_sapiens_GCA_000001405_27
        image:
          type: string
          example: http://2020.ensembl.org/static/genome_images/homo_sapiens_GCA_000001405_27.svg
        is_available:
          type: boolean
          example: true
        popular_order:
          type: integer
          format: int32
          example: 0
        reference_genome_id:
          type: string
          example: null
        scientific_name:
          type: string
          example: Homo sapiens
        division_ids:
          type: array
          items:
            $ref: '#/components/schemas/Division/properties/division_name'
    Division:
      type: object
      properties:
        division_name:
          type: string
          example: EnsemblVertebrates
    Assembly:
      type: object
      properties:
        assembly_name:
          type: string
          example: GRCh37.p13
        genome_id:
          type: string
          example: homo_sapiens_GCA_000001405_14
    TrackCategory:
      type: object
      properties:
        track_category_id:
          type: string
          example: genes-transcripts
        label:
          type: string
          example: Genes & transcripts
        track_list:
          type: array
          items:
            $ref: '#/components/schemas/Track'
        types:
          type: array
          items:
            type: string
            enum:
            - Genomic
            - Variation
            - Expression
    Track:
      type: object
      properties:
        track_id:
          type: string
          example: track:gene-pc-fwd
        label:
          type: string
          example: Protein coding genes
        color:
          type: string
          example: GREY
        additional_info:
          type: string
          example: Forward strand

