ASSOCIATED_ASSEMBLIES:
      human:
          - 'a7335667-93e7-11ec-a39d-005056b38ce3'
          - '3704ceb1-948d-11ec-a39d-005056b38ce3'
      test:
          - 'wheat_test1'
          - 'wheat_test2'
          - 'wheat_test3'
          - 'wheat_test4'
          - 'wheat_test5'
          - 'wheat_test6'
POPULAR_GENOMES:
      'a7335667-93e7-11ec-a39d-005056b38ce3':
              Order: 0
              Icon: 'homo_sapiens_38.svg'
      'mus_musculus_GCA_000001635_9':
              Order: 1
              Icon: 'mus_musculus.svg'
      'danio_rerio_GCA_000002035_4':
              Order: 2
              Icon: 'danio_rerio.svg'
      'a73357ab-93e7-11ec-a39d-005056b38ce3':
              Order: 3
              Icon: 'triticum_aestivum.svg'
      'oryza_sativa_GCA_001433935_1':
              Order: 4
              Icon: 'oryza_sativa.svg'
      'arabidopsis_thaliana_GCA_000001735_1':
              Order: 5
              Icon: 'arabidopsis_thaliana.svg'
      '3704ceb1-948d-11ec-a39d-005056b38ce3':
              Order: 6
              Icon: 'homo_sapiens_37.svg'
      'bos_taurus_GCA_002263795_2':
              Order: 7
              Icon: 'bos_taurus.svg'
      'rattus_norvegicus_GCA_000001895_4':
              Order: 8
              Icon: 'rattus_norvegicus.svg'
      'sus_scrofa_GCA_000003025_6':
              Order: 9
              Icon: 'sus_scrofa.svg'
      'zea_mays_GCA_902167145_1':
              Order: 10
              Icon: 'zea_mays.svg'
      'gallus_gallus_GCA_000002315_5':
              Order: 11
              Icon: 'gallus_gallus.svg'
      'canis_familiaris_GCA_000002285_2':
              Order: 12
              Icon: 'canis_familiaris.svg'
      'hordeum_vulgare_GCA_901482405_1':
              Order: 13
              Icon: 'hordeum_vulgare.svg'
      'drosophila_melanogaster_GCA_000001215_4':
              Order: 14
              Icon: 'drosophila_melanogaster.svg'
      'oryzias_latipes_GCA_002234675_1':
              Order: 15
              Icon: 'oryzias_latipes.svg'
      'ovis_aries_GCA_000298735_1':
              Order: 16
              Icon: 'ovis_aries.svg'
      'vitis_vinifera_GCA_000003745_2':
              Order: 17
              Icon: 'vitis_vinifera.svg'
      'solanum_lycopersicum_GCA_000188115_3':
              Order: 18
              Icon: 'solanum_lycopersicum.svg'
      'a733550b-93e7-11ec-a39d-005056b38ce3':
              Order: 19
              Icon: 'caenorhabditis_elegans.svg'
      'equus_caballus_GCA_002863925_1':
              Order: 20
              Icon: 'equus_caballus.svg'
      'brassica_napus_GCA_000751015_1':
              Order: 21
              Icon: 'brassica_napus.svg'
      'solanum_tuberosum_GCA_000226075_1':
              Order: 22
              Icon: 'solanum_tuberosum.svg'
      'oryctolagus_cuniculus_GCA_000003625_1':
              Order: 23
              Icon: 'oryctolagus_cuniculus.svg'
      'a733574a-93e7-11ec-a39d-005056b38ce3_2':
              Order: 24
              Icon: 'saccharomyces_cerevisiae.svg'
      'felis_catus_GCA_000181335_4':
              Order: 25
              Icon: 'felis_catus.svg'
      'macaca_mulatta_GCA_003339765_3':
              Order: 26
              Icon: 'macaca_mulatta.svg'
      'astyanax_mexicanus_GCA_000372685_2':
              Order: 27
              Icon: 'astyanax_mexicanus.svg'
      'pan_troglodytes_GCA_000001515_5':
              Order: 28
              Icon: 'pan_troglodytes.svg'
      'oreochromis_niloticus_GCA_001858045_3':
              Order: 29
              Icon: 'oreochromis_niloticus.svg'
      'capra_hircus_GCA_001704415_1':
              Order: 30
              Icon: 'capra_hircus.svg'
      'brassica_oleracea_GCA_000695525_1':
              Order: 31
              Icon: 'brassica_oleracea.svg'
      'xenopus_tropicalis_GCA_000004195_3':
              Order: 32
              Icon: 'xenopus_tropicalis.svg'
      'glycine_max_GCA_000004515_4':
              Order: 33
              Icon: 'glycine_max.svg'
      'cricetulus_griseus_GCA_003668045_1':
              Order: 34
              Icon: 'cricetulus_griseus.svg'
      'medicago_truncatula_GCA_000219495_2':
              Order: 35
              Icon: 'medicago_truncatula.svg'
      'brassica_rapa_GCA_000309985_1':
              Order: 36
              Icon: 'brassica_rapa.svg'
      'sorghum_bicolor_GCA_000003195_3':
              Order: 37
              Icon: 'sorghum_bicolor.svg'
      'salmo_salar_GCA_000233375_4':
              Order: 38
              Icon: 'salmo_salar.svg'
      'aegilops_tauschii_GCA_002575655_1':
              Order: 39
              Icon: 'aegilops_tauschii.svg'
      'a733574a-93e7-11ec-a39d-005056b38ce3':
              Order: 40
              Icon: 'escherichia_coli.svg'
      'a73356e1-93e7-11ec-a39d-005056b38ce3':
              Order: 41
              Icon: 'plasmodium_falciparum.svg'
AVAILABLE_GENOMES:
      'a7335667-93e7-11ec-a39d-005056b38ce3':
              Gene: 'ENSG00000139618'
              Region: '17:63992802-64038237'
      '3704ceb1-948d-11ec-a39d-005056b38ce3':
              Gene: 'ENSG00000139618'
              Region: '17:64155265-64255266'
      'a73357ab-93e7-11ec-a39d-005056b38ce3':
              Gene: 'TraesCS3D02G273600'
              Region: '3D:2585940-2634711'
      'a733574a-93e7-11ec-a39d-005056b38ce3_2':
              Gene: 'YDL168W'
              Region: 'VII:786054-786920'
      'a733574a-93e7-11ec-a39d-005056b38ce3':
              Gene: 'b2614'
              Region: 'Chromosome:2750115-2750708'
      'a733550b-93e7-11ec-a39d-005056b38ce3':
              Gene: 'WBGene00004893'
              Region: 'X:937766-957832'
      'a73356e1-93e7-11ec-a39d-005056b38ce3':
              Gene: 'PF3D7_1143500'
              Region: '11:1737256-1740029'
