ASSOCIATED_ASSEMBLIES:
      test:
          - 'homo_sapiens_GCA_000001405_27'
          - 'homo_sapiens_GCA_000001405_14'
      test2:
          - 'wheat_test1'
          - 'wheat_test2'
          - 'wheat_test3'
          - 'wheat_test4'
          - 'wheat_test5'
          - 'wheat_test6'
POPULAR_GENOMES:
      - 'homo_sapiens_GCA_000001405_27'
      - 'mus_musculus_pwkphj_GCA_001624775_1'
      - 'mus_musculus_c57bl6nj_GCA_001632555_1'
      - 'mus_musculus_cbaj_GCA_001624475_1'
      - 'mus_musculus_129s1svimj_GCA_001624185_1'
AVAILABLE_GENOMES:
      - 'homo_sapiens_GCA_000001405_27'
      - 'homo_sapiens_GCA_000001405_14'
      - 'mus_musculus_129s1svimj_GCA_001624185_1'