ASSOCIATED_ASSEMBLIES:
      human:
          - 'homo_sapiens_GCA_000001405_28'
          - 'homo_sapiens_GCA_000001405_14'
      test:
          - 'wheat_test1'
          - 'wheat_test2'
          - 'wheat_test3'
          - 'wheat_test4'
          - 'wheat_test5'
          - 'wheat_test6'
POPULAR_GENOMES:
      - 'homo_sapiens_GCA_000001405_28'
      - 'mus_musculus_GCA_000001635_9'
      - 'danio_rerio_GCA_000002035_4'
      - 'triticum_aestivum_GCA_900519105_1'
      - 'oryza_sativa_GCA_001433935_1'
      - 'arabidopsis_thaliana_GCA_000001735_1'
      - 'homo_sapiens_GCA_000001405_14'
      - 'bos_taurus_GCA_002263795_2'
      - 'rattus_norvegicus_GCA_000001895_4'
      - 'sus_scrofa_GCA_000003025_6'
      - 'zea_mays_GCA_902167145_1'
      - 'gallus_gallus_GCA_000002315_5'
      - 'canis_familiaris_GCA_000002285_2'
      - 'hordeum_vulgare_GCA_901482405_1'
      - 'drosophila_melanogaster_GCA_000001215_4'
      - 'oryzias_latipes_GCA_002234675_1'
      - 'ovis_aries_GCA_000298735_1'
      - 'vitis_vinifera_GCA_000003745_2'
      - 'solanum_lycopersicum_GCA_000188115_3'
      - 'caenorhabditis_elegans_GCA_000002985_3'
      - 'equus_caballus_GCA_002863925_1'
      - 'brassica_napus_GCA_000751015_1'
      - 'solanum_tuberosum_GCA_000226075_1'
      - 'oryctolagus_cuniculus_GCA_000003625_1'
      - 'saccharomyces_cerevisiae_GCA_000146045_2'
      - 'felis_catus_GCA_000181335_4'
      - 'macaca_mulatta_GCA_003339765_3'
      - 'astyanax_mexicanus_GCA_000372685_2'
      - 'pan_troglodytes_GCA_000001515_5'
      - 'oreochromis_niloticus_GCA_001858045_3'
      - 'capra_hircus_GCA_001704415_1'
      - 'brassica_oleracea_GCA_000695525_1'
      - 'xenopus_tropicalis_GCA_000004195_3'
      - 'glycine_max_GCA_000004515_4'
      - 'cricetulus_griseus_GCA_003668045_1'
      - 'medicago_truncatula_GCA_000219495_2'
      - 'brassica_rapa_GCA_000309985_1'
      - 'sorghum_bicolor_GCA_000003195_3'
      - 'salmo_salar_GCA_000233375_4'
      - 'aegilops_tauschii_GCA_002575655_1'
      - 'escherichia_coli_str_k_12_substr_mg1655_gca_000005845_GCA_000005845_2'
      - 'plasmodium_falciparum_GCA_000002765_2'
AVAILABLE_GENOMES:
      'homo_sapiens_GCA_000001405_28':
              Gene: 'ENSG00000139618'
              Region: '17:63992802-64038237'
      'homo_sapiens_GCA_000001405_14':
              Gene: 'ENSG00000139618'
              Region: '17:64155265-64255266'
      'triticum_aestivum_GCA_900519105_1':
              Gene: 'TraesCS3D02G273600'
              Region: '3D:2585940-2634711'
      'saccharomyces_cerevisiae_GCA_000146045_2':
              Gene: 'YDL168W'
              Region: 'VII:786054-786920'
      'escherichia_coli_str_k_12_substr_mg1655_gca_000005845_GCA_000005845_2':
              Gene: 'b2614'
              Region: 'Chromosome:2750115-2750708'
      'caenorhabditis_elegans_GCA_000002985_3':
              Gene: 'WBGene00004893'
              Region: 'X:937766-957832'
      'plasmodium_falciparum_GCA_000002765_2':
              Gene: 'PF3D7_1143500'
              Region: '11:1737256-1740029'
