ASSOCIATED_ASSEMBLIES:
      human:
          - 'homo_sapiens_GCA_000001405_27'
          - 'homo_sapiens_GCA_000001405_14'
      test:
          - 'wheat_test1'
          - 'wheat_test2'
          - 'wheat_test3'
          - 'wheat_test4'
          - 'wheat_test5'
          - 'wheat_test6'
POPULAR_GENOMES:
      - 'homo_sapiens_GCA_000001405_27'
      - 'mus_musculus_GCA_000001635_8'
      - 'triticum_aestivum_GCA_900519105_1'
      - 'homo_sapiens_GCA_000001405_14'
      - 'danio_rerio_GCA_000002035_4'
      - 'hordeum_vulgare_tbd'
      - 'arabidopsis_thaliana_GCA_000001735_1'
      - 'zea_mays_GCA_000005005_6'
      - 'oryza_sativa_GCA_001433935_1'
      - 'gallus_gallus_GCA_000002315_5'
      - 'rattus_norvegicus_GCA_000001895_4'
      - 'sus_scrofa_GCA_000003025_6'
      - 'bos_taurus_GCA_002263795_2'
      - 'magnaporthe_oryzae_GCA_000002495_2'
      - 'botrytis_cinerea_GCA_000143535_4'
      - 'canis_familiaris_GCA_000002285_2'
      - 'schizosaccharomyces_pombe_GCA_000002945_2'
      - 'phaeodactylum_tricornutum_GCA_000150955_2'
      - 'drosophila_melanogaster_GCA_000001215_4'
      - 'escherichia_coli_str_k_12_substr_mg1655_GCA_000005845_2'
      - 'fusarium_graminearum_GCA_900044135_1'
      - 'ovis_aries_GCA_000298735_1'
      - 'oryzias_latipes_GCA_002234675_1'
      - 'lactobacillus_delbrueckii_subsp_bulgaricus_2038_GCA_000191165_1'
      - 'saccharomyces_cerevisiae_GCA_000146045_2'
      - 'caenorhabditis_elegans_GCA_000002985_3'
      - 'zymoseptoria_tritici_GCA_000219625_1'
      - 'equus_caballus_GCA_002863925_1'
      - 'tribolium_castaneum_GCA_000002335_3'
      - 'bombyx_mori_GCA_000151625_1'
      - 'aspergillus_fumigatusa1163_GCA_000150145_1'
      - 'neurospora_crassa_GCA_000182925_2'
      - 'zootermopsis_nevadensis_GCA_000696155_1'
      - 'anopheles_gambiae_GCA_000005575_1'
      - 'apis_mellifera_GCA_000002195_1'
      - 'schizosaccharomyces_japonicus_GCA_000149845_2'
      - 'macaca_mulatta_GCA_000772875_3'
      - 'phytophthora_infestans_GCA_000142945_1'
      - 'fusarium_oxysporum_GCA_000222805_1'
      - 'oreochromis_niloticus_GCA_000188235_1'
      - 'salpingoeca_rosetta_GCA_000188695_1'
      - 'plasmodium_falciparum_GCA_000002765_2'
AVAILABLE_GENOMES:
      'homo_sapiens_GCA_000001405_27':
              Gene: 'ENSG00000139618'
              Region: '17:63992802-64038237'
      'homo_sapiens_GCA_000001405_14':
              Gene: 'ENSG00000139618'
              Region: '17:64155265-64255266'
      'triticum_aestivum_GCA_900519105_1':
              Gene: 'TraesCS3D02G273600'
              Region: '3D:2585940-2634711'
      'saccharomyces_cerevisiae_GCA_000146045_2':
              Gene: 'YDL168W'
              Region: 'VII:786054-786920'
      'escherichia_coli_str_k_12_substr_mg1655_GCA_000005845_2':
              Gene: 'b2614'
              Region: 'Chromosome:2750115-2750708'
      'caenorhabditis_elegans_GCA_000002985_3':
              Gene: 'WBGene00004893'
              Region: 'X:937766-957832'
      'plasmodium_falciparum_GCA_000002765_2':
              Gene: 'PF3D7_1143500'
              Region: '11:1737256-1740029'
