ASSOCIATED_ASSEMBLIES:
      test:
          - 'homo_sapiens_GCA_000001405_27'
          - 'homo_sapiens_GRCh37'
          - 'homo_sapiens_GRCh36'
      test2:
          - 'wheat-test1'
          - 'wheat-test2'
          - 'wheat-test3'
          - 'wheat-test4'
          - 'wheat-test5'
          - 'wheat-test6'
POPULAR_GENOMES:
      - 'homo_sapiens_GCA_000001405_27'
      - 'mus_musculus_pwkphj_GCA_001624775_1'
      - 'mus_musculus_c57bl6nj_GCA_001632555_1'
      - 'mus_musculus_cbaj_GCA_001624475_1'
      - 'mus_musculus_129s1svimj_GCA_001624185_1'
AVAILABLE_GENOMES:
      - 'homo_sapiens_GCA_000001405_27'
      - 'mus_musculus_129s1svimj_GCA_001624185_1'