###################################################################################################################
# Common configuration
###################################################################################################################

VALID_DIVISIONS:
  'EB': 'EnsemblBacteria'
  'EF': 'EnsemblFungi'
  'EM': 'EnsemblMetazoa'
  'EPl': 'EnsemblPlants'
  'EPr': 'EnsemblProtists'
  'EV': 'EnsemblVertebrates'

GENOME_STORE_FILE: 'genome_store.json'
INDEX_FILE: 'index.json'
REGION_INFO_FILE: 'region_info_store.json'

DEBUG: True

BACKEND_GENERIC_REST_URL: 'https://rest.ensembl.org'
BACKEND_GRCH37_REST_URL: 'https://grch37.rest.ensembl.org'

###################################################################################################################
# Indexer specific configuration
###################################################################################################################

STOP_CHARS_MAPPING:
  '_': ' '
  '-': ''
  '(': ' '
  ')': ' '
  '[': ' '
  ']': ' '

KEYS_TO_INDEX:
  - 'common_name'
  - 'scientific_name'
  - 'assembly_name'

MINIMUM_TOKEN_LENGTH: 3

###################################################################################################################
# Genome Fetch configuration
###################################################################################################################
GENOME_ID_VALID_CHARS: 'A-Za-z0-9'



V_VERSION: 96

METADATA_REGISTRY_URL: 'http://test-metadata.ensembl.org/genome'

###################################################################################################################
# Update the following path accordingly
###################################################################################################################

DATA_FILE_PATH: '/usr/src/genome-search'

